# Generated by Django 2.2.2 on 2019-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='blood_group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='dept',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='hall',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='hometown',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='program',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='room',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
