# Generated by Django 2.2.2 on 2019-06-21 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_medicine_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
