# Generated by Django 2.2.2 on 2019-06-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0003_auto_20190621_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='user',
        ),
    ]
