# Generated by Django 2.2.2 on 2019-06-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='timings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Timing'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='tests',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Doctor.Test'),
        ),
    ]
