# Generated by Django 2.2.2 on 2019-07-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presmedicine',
            name='provided',
            field=models.BooleanField(default=False),
        ),
    ]
