# Generated by Django 2.2.3 on 2019-07-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayAndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('visitDay', models.ManyToManyField(to='Doctor.Day')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='timings',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='visitDays',
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
