# Generated by Django 2.2.2 on 2019-06-21 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20190621_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Test'),
        ),
    ]
