# Generated by Django 2.2.3 on 2019-07-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20190706_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='visit_day_time',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Doctor.DayAndTime'),
        ),
    ]
