# Generated by Django 2.2.2 on 2019-06-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20190623_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='timings',
        ),
    ]
