# Generated by Django 2.2.2 on 2019-06-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20190621_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='vitals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seven.bodyVital'),
        ),
    ]
