# Generated by Django 2.2.2 on 2019-07-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_auto_20190709_0435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PresConsultDetails',
            new_name='PresDetails',
        ),
    ]
