# Generated by Django 2.2.2 on 2019-06-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_remove_doctor_timings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='visitDays',
        ),
        migrations.AddField(
            model_name='doctor',
            name='visitDays',
            field=models.ManyToManyField(to='Doctor.Day'),
        ),
    ]
