# Generated by Django 2.2.2 on 2019-06-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seven', '0003_auto_20190626_1912'),
        ('Doctor', '0006_auto_20190623_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='timings',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Doctor.Timing'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='vitals',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seven.bodyVital'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='tests',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seven.Test'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
