# Generated by Django 2.2.2 on 2019-06-27 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seven', '0003_auto_20190626_1912'),
        ('Patient', '0004_auto_20190628_0020'),
        ('Doctor', '0007_auto_20190626_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='vitals',
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='roomNo7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatmentFor',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='timings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Timing'),
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='tests',
        ),
        migrations.AddField(
            model_name='prescription',
            name='tests',
            field=models.ManyToManyField(blank=True, to='seven.Test'),
        ),
        migrations.CreateModel(
            name='PresMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('times_a_day', models.PositiveIntegerField()),
                ('no_of_days', models.PositiveIntegerField()),
                ('when_to_take', models.CharField(choices=[('b', 'Before meal'), ('a', 'After meal'), ('n', 'Night')], default='a', max_length=1)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Prescription')),
            ],
        ),
    ]
