# Generated by Django 2.2.2 on 2019-06-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0009_temppres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temppres',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='temppres',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Prescription'),
        ),
    ]
