# Generated by Django 2.2.2 on 2019-06-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_auto_20190628_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
