# Generated by Django 2.2.2 on 2019-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0011_auto_20190628_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='med_added',
            field=models.BooleanField(default=False),
        ),
    ]
