# Generated by Django 2.2.2 on 2019-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0012_prescription_med_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='treatmentFor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='TempPres',
        ),
    ]
