# Generated by Django 2.2.2 on 2019-07-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0013_auto_20190702_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='treatmentFor',
            field=models.TextField(blank=True),
        ),
    ]
