# Generated by Django 2.2.2 on 2019-07-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0014_auto_20190703_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doc_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doc_ref', to='Doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refer_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='Doctor.Doctor'),
        ),
    ]
