# Generated by Django 2.2.2 on 2019-07-06 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0015_auto_20190706_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doc_ref',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='refer_remarks',
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks_from_doc', models.TextField(blank=True)),
                ('remarks_to_doc', models.TextField(blank=True)),
                ('from_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_doc', to='Doctor.Doctor')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Prescription')),
                ('to_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_doc', to='Doctor.Doctor')),
            ],
        ),
    ]
