# Generated by Django 2.2.2 on 2019-07-06 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0001_initial'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateNtime', models.DateTimeField(auto_now_add=True)),
                ('brief', models.TextField(blank=True)),
                ('reqApproval', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('refer_remarks', models.TextField(blank=True)),
                ('doc_ref', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_ref', to='Doctor.Doctor')),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='Doctor.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Prescription')),
            ],
        ),
        migrations.CreateModel(
            name='ReferredAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_app', to='Reception.Appointment')),
                ('prev_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_app', to='Reception.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
