# Generated by Django 2.2.2 on 2019-07-05 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient'),
        ),
        migrations.CreateModel(
            name='ReferredAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_app', to='Reception.Appointment')),
                ('prev_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_app', to='Reception.Appointment')),
            ],
        ),
    ]
