# Generated by Django 2.2.2 on 2019-07-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0003_auto_20190706_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doc_ref',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='refer_remarks',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient'),
        ),
        migrations.DeleteModel(
            name='ReferredAppointment',
        ),
    ]
