# Generated by Django 2.2.2 on 2019-06-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0002_auto_20190621_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodyVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodPressure', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('height', models.CharField(max_length=10)),
                ('sugarLevel', models.CharField(max_length=20)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Prescription')),
            ],
        ),
    ]
