# Generated by Django 2.2.3 on 2019-07-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodPress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_press', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='bodyTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_temp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sugarLvl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_level', models.IntegerField(default=0)),
            ],
        ),
    ]
