# Generated by Django 2.2.3 on 2019-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven', '0002_bloodpress_bodytemp_sugarlvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpress',
            name='blood_press',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='bodytemp',
            name='body_temp',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='sugarlvl',
            name='sugar_level',
            field=models.CharField(max_length=4),
        ),
    ]
