# Generated by Django 2.2.2 on 2019-06-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_auto_20190628_0021'),
        ('seven', '0003_auto_20190626_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='TestList',
        ),
        migrations.RemoveField(
            model_name='bodyvital',
            name='bloodPressure',
        ),
        migrations.RemoveField(
            model_name='bodyvital',
            name='height',
        ),
        migrations.RemoveField(
            model_name='bodyvital',
            name='sugarLevel',
        ),
        migrations.RemoveField(
            model_name='bodyvital',
            name='weight',
        ),
        migrations.AddField(
            model_name='bodyvital',
            name='testName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodyvital',
            name='value',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
