# Generated by Django 2.2.3 on 2019-07-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20190708_0325'),
        ('seven', '0003_auto_20190707_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bloodPress',
        ),
        migrations.DeleteModel(
            name='bodyTemp',
        ),
        migrations.DeleteModel(
            name='sugarLvl',
        ),
        migrations.DeleteModel(
            name='TestList',
        ),
        migrations.RemoveField(
            model_name='bodyvital',
            name='testName',
        ),
        migrations.RemoveField(
            model_name='bodyvital',
            name='value',
        ),
        migrations.AddField(
            model_name='bodyvital',
            name='blood_press',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodyvital',
            name='body_temp',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodyvital',
            name='prescription',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Doctor.Prescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodyvital',
            name='remarks',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodyvital',
            name='sugar_level',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
    ]
