# Generated by Django 2.2.2 on 2019-07-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='types',
            field=models.CharField(choices=[('phr', 'Pharmacy'), ('rec', 'Reception'), ('doc', 'Doctor'), ('pat', 'Patient'), ('vit', 'vitals')], default='pat', max_length=3),
        ),
    ]
