# Generated by Django 2.2.2 on 2019-06-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190620_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bodyVitals',
            new_name='bodyVital',
        ),
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
        migrations.RenameModel(
            old_name='Medicines',
            new_name='Medicine',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
    ]
