# Generated by Django 2.2.2 on 2019-06-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190620_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='visitDays',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='tests',
        ),
        migrations.AlterField(
            model_name='bodyvital',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Prescription'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='HCDept',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
