# Generated by Django 2.2.2 on 2019-06-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190621_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyvital',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='bodyVital',
        ),
    ]
