# Generated by Django 2.2.2 on 2019-06-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='types',
            field=models.CharField(choices=[('phr', 'Pharmacy'), ('rec', 'Reception'), ('doc', 'Doctor'), ('pat', 'Patient')], default='pat', max_length=3),
        ),
    ]
