# Generated by Django 2.2.2 on 2019-06-21 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('bloodGroup', models.CharField(max_length=10)),
                ('drugAllergies', models.CharField(max_length=500)),
                ('significantMedicalHistory', models.CharField(max_length=5000)),
                ('phoneNo', models.CharField(max_length=15)),
                ('emergencyContactName', models.CharField(max_length=50)),
                ('emergencyContactNo', models.CharField(max_length=15)),
                ('rollNo', models.CharField(max_length=15)),
                ('dependentName', models.CharField(max_length=50)),
                ('dependentRelation', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=15)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Prescription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
