# Generated by Django 2.2.2 on 2019-06-26 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0006_auto_20190623_1149'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('bloodGroup', models.CharField(blank=True, max_length=10)),
                ('drugAllergies', models.CharField(default='none', max_length=500)),
                ('significantMedicalHistory', models.CharField(default='none', max_length=5000)),
                ('phoneNo', models.CharField(max_length=15)),
                ('emergencyContactName', models.CharField(max_length=50)),
                ('emergencyContactNo', models.CharField(max_length=15)),
                ('emergencyContactRelation', models.CharField(max_length=20)),
                ('rollNo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('is_dependent', models.BooleanField(default=True)),
                ('dependentUser', models.CharField(blank=True, max_length=25)),
                ('dependentRelation', models.CharField(blank=True, max_length=15)),
                ('designation', models.CharField(blank=True, max_length=15)),
                ('department', models.CharField(blank=True, max_length=15)),
                ('prescription', models.ManyToManyField(blank=True, to='Doctor.Prescription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
