# Generated by Django 2.2.2 on 2019-06-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergencyContactRelation',
            field=models.CharField(default='', max_length=20),
        ),
    ]
