# Generated by Django 2.2.2 on 2019-06-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20190627_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
        migrations.CreateModel(
            name='PatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentFor', models.CharField(max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('files', models.FileField(blank=True, upload_to='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient')),
            ],
        ),
    ]
