# Generated by Django 2.2.2 on 2019-07-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_auto_20190703_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
