# Generated by Django 2.2.2 on 2019-07-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_patient_is_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='drugAllergies',
            new_name='allergies',
        ),
    ]
