# Generated by Django 2.2.2 on 2019-07-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20190703_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathistory',
            old_name='files',
            new_name='file',
        ),
        migrations.AddField(
            model_name='pathistory',
            name='file_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
